QBShared = QBShared or {}
QBShared.Items = {
	---Materials
	--Scraps
	['scrapmetal'] 					 = {['name'] = 'scrapmetal', 			  	  	['label'] = 'Scrap Metal', 				['weight'] = 100, 		['type'] = 'item', 		['image'] = 'metalscrap.png', 			['unique'] = false, 	['useable'] = false, 	['shouldClose'] = false,   ['combinable'] = nil,   ['description'] = 'You can probably make something nice out of this'},
	['scrapcloth'] 					 = {['name'] = 'scrapcloth', 			  	   	['label'] = 'Scrap Cloth', 				['weight'] = 10, 		['type'] = 'item', 		['image'] = 'scrapcloth.png', 				['unique'] = false, 	['useable'] = false, 	['shouldClose'] = false,    ['combinable'] = nil,   ['description'] = 'Scrap Cloth, should be able to make something out of this if i take this somewhere'},
	['scrappaper'] 					 = {['name'] = 'scrappaper', 			  	  	['label'] = 'Scrap Paper', 				['weight'] = 100, 		['type'] = 'item', 		['image'] = 'scrap_paper.png', 			['unique'] = false, 	['useable'] = false, 	['shouldClose'] = false,   ['combinable'] = nil,   ['description'] = 'You can probably make something nice out of this'},
	['scrapplastic'] 					 = {['name'] = 'scrapplastic', 			  	   	['label'] = 'Scrap Plastic', 				['weight'] = 10, 		['type'] = 'item', 		['image'] = 'scrap_plastic.png', 				['unique'] = false, 	['useable'] = false, 	['shouldClose'] = false,    ['combinable'] = nil,   ['description'] = 'Scrap Cloth, should be able to make something out of this if i take this somewhere'},
	['scraprubber'] 					 = {['name'] = 'scraprubber', 			  	  	['label'] = 'Scrap Rubber', 				['weight'] = 100, 		['type'] = 'item', 		['image'] = 'scrap_rubber.png', 			['unique'] = false, 	['useable'] = false, 	['shouldClose'] = false,   ['combinable'] = nil,   ['description'] = 'You can probably make something nice out of this'},
	['scrapglass'] 					 = {['name'] = 'scrapglass', 			  	   	['label'] = 'Scrap Glass', 				['weight'] = 10, 		['type'] = 'item', 		['image'] = 'scrap_glass.png', 				['unique'] = false, 	['useable'] = false, 	['shouldClose'] = false,    ['combinable'] = nil,   ['description'] = 'Scrap Cloth, should be able to make something out of this if i take this somewhere'},
	['scrapewaste'] 					 = {['name'] = 'scrapewaste', 			  	  	['label'] = 'Scrap E-Waste', 				['weight'] = 100, 		['type'] = 'item', 		['image'] = 'scrap_ewaste.png', 			['unique'] = false, 	['useable'] = false, 	['shouldClose'] = false,   ['combinable'] = nil,   ['description'] = 'You can probably make something nice out of this'},
	['scraporganic'] 					 = {['name'] = 'scraporganic', 			  	   	['label'] = 'Scrap Organic', 				['weight'] = 10, 		['type'] = 'item', 		['image'] = 'scrap_organic.png', 				['unique'] = false, 	['useable'] = false, 	['shouldClose'] = false,    ['combinable'] = nil,   ['description'] = 'Scrap Cloth, should be able to make something out of this if i take this somewhere'},
	--Scrap Bags
	['scrapwhitebag'] 					 = {['name'] = 'scrapwhitebag', 			  	  	['label'] = 'White Bin Bag', 				['weight'] = 100, 		['type'] = 'item', 		['image'] = 'scrap_whitebag.png', 			['unique'] = false, 	['useable'] = false, 	['shouldClose'] = false,   ['combinable'] = nil,   ['description'] = 'You can probably make something nice out of this'},
	['scrapblackbag'] 					 = {['name'] = 'scrapblackbag', 			  	   	['label'] = 'Black Bin Bag', 				['weight'] = 100, 		['type'] = 'item', 		['image'] = 'scrap_blackbag.png', 				['unique'] = false, 	['useable'] = false, 	['shouldClose'] = false,    ['combinable'] = nil,   ['description'] = 'Scrap Cloth, should be able to make something out of this if i take this somewhere'},
	--Crates
	["crate_random"] 						 = {["name"] = "crate_random",					["label"] = "crate random",					["weight"] = 500,		["type"] = "item",		["image"] = "crate_random.png",				["unique"] = false, 	["useable"] = false,	["shouldClose"] = false,	["combinable"] = nil,	["description"] = "a nice beverage"},
	
	["crate_drugs"] 						 = {["name"] = "crate_drugs",					["label"] = "crate drugs",					["weight"] = 500,		["type"] = "item",		["image"] = "crate_drugs.png",				["unique"] = false, 	["useable"] = false,	["shouldClose"] = false,	["combinable"] = nil,	["description"] = "a nice beverage"},
	["crate_food"] 						 = {["name"] = "crate_food",					["label"] = "crate food",					["weight"] = 500,		["type"] = "item",		["image"] = "crate_food.png",				["unique"] = false, 	["useable"] = false,	["shouldClose"] = false,	["combinable"] = nil,	["description"] = "a nice beverage"},
	["crate_gem"] 						 = {["name"] = "crate_gem",					["label"] = "crate gem",					["weight"] = 500,		["type"] = "item",		["image"] = "crate_gem.png",				["unique"] = false, 	["useable"] = false,	["shouldClose"] = false,	["combinable"] = nil,	["description"] = "a nice beverage"},
	["crate_medical"] 						 = {["name"] = "crate_medical",					["label"] = "crate medical",					["weight"] = 500,		["type"] = "item",		["image"] = "crate_medical.png",				["unique"] = false, 	["useable"] = false,	["shouldClose"] = false,	["combinable"] = nil,	["description"] = "a nice beverage"},
	["crate_supplies"] 						 = {["name"] = "crate_supplies",					["label"] = "crate supplies",					["weight"] = 500,		["type"] = "item",		["image"] = "crate_supplies.png",				["unique"] = false, 	["useable"] = false,	["shouldClose"] = false,	["combinable"] = nil,	["description"] = "a nice beverage"},
	["crate_tools"] 						 = {["name"] = "crate_tools",					["label"] = "crate tools",					["weight"] = 500,		["type"] = "item",		["image"] = "crate_tools.png",				["unique"] = false, 	["useable"] = false,	["shouldClose"] = false,	["combinable"] = nil,	["description"] = "a nice beverage"},
	["crate_weapon"] 						 = {["name"] = "crate_weapon",					["label"] = "crate weapon",					["weight"] = 500,		["type"] = "item",		["image"] = "crate_weapon.png",				["unique"] = false, 	["useable"] = false,	["shouldClose"] = false,	["combinable"] = nil,	["description"] = "a nice beverage"},
	["crate_beverage"] 						 = {["name"] = "crate_beverage",					["label"] = "Crate Beverage",					["weight"] = 500,		["type"] = "item",		["image"] = "crate_beverage.png",				["unique"] = false, 	["useable"] = false,	["shouldClose"] = false,	["combinable"] = nil,	["description"] = "a nice beverage"},
	["crate_ore"] 						 = {["name"] = "crate_ore",					["label"] = "Crate Ore's",					["weight"] = 500,		["type"] = "item",		["image"] = "crate_ore.png",				["unique"] = false, 	["useable"] = false,	["shouldClose"] = false,	["combinable"] = nil,	["description"] = "a nice beverage"},
	["crate_smoke"] 						 = {["name"] = "crate_smoke",					["label"] = "Crate Cigarette",					["weight"] = 500,		["type"] = "item",		["image"] = "crate_smoke.png",				["unique"] = false, 	["useable"] = false,	["shouldClose"] = false,	["combinable"] = nil,	["description"] = "a nice beverage"},

	
	--Broken Parts
	["broken_axel"]=          {["name"] = "broken_axel",        ["label"] = "Broken Axel",			["weight"] = 0, ["type"] = "item",  ["image"] = "broken_axel.png",        ["unique"] = false,  ["useable"] = false,["shouldClose"] = false,["description"] = ""},
	["broken_brake_caliper"]=          {["name"] = "broken_brake_caliper",        ["label"] = "Broken Caliper",			["weight"] = 0, ["type"] = "item",  ["image"] = "broken_brake_caliper.png",        ["unique"] = false,  ["useable"] = false,["shouldClose"] = false,["description"] = ""},
	["broken_brakedisc"]=          {["name"] = "broken_brakedisc",        ["label"] = "Broken Disc",			["weight"] = 0, ["type"] = "item",  ["image"] = "Broken_brakedisc.png",        ["unique"] = false,  ["useable"] = false,["shouldClose"] = false,["description"] = ""},
	["broken_engineblock"]=          {["name"] = "broken_engineblock",        ["label"] = "Broken Engine Block",			["weight"] = 0, ["type"] = "item",  ["image"] = "broken_engineblock.png",        ["unique"] = false,  ["useable"] = false,["shouldClose"] = false,["description"] = ""},
	["broken_manifold"]=          {["name"] = "broken_manifold",        ["label"] = "Broken Manifold",			["weight"] = 0, ["type"] = "item",  ["image"] = "broken_manifold.png",        ["unique"] = false,  ["useable"] = false,["shouldClose"] = false,["description"] = ""},
	["broken_piston"]=          {["name"] = "broken_piston",        ["label"] = "Broken Piston",			["weight"] = 0, ["type"] = "item",  ["image"] = "broken_piston.png",        ["unique"] = false,  ["useable"] = false,["shouldClose"] = false,["description"] = ""},
	["broken_rim"]=          {["name"] = "broken_rim",        ["label"] = "Broken Rim",			["weight"] = 0, ["type"] = "item",  ["image"] = "broken_rim.png",        ["unique"] = false,  ["useable"] = false,["shouldClose"] = false,["description"] = ""},
	["broken_suspension"]=          {["name"] = "broken_suspension",        ["label"] = "Broken Suspension",			["weight"] = 0, ["type"] = "item",  ["image"] = "broken_suspension.png",        ["unique"] = false,  ["useable"] = false,["shouldClose"] = false,["description"] = ""},
	["broken_suspension_arm"]=          {["name"] = "broken_suspension_arm",        ["label"] = "Broken Suspension Arm",			["weight"] = 0, ["type"] = "item",  ["image"] = "broken_suspension_arm.png",        ["unique"] = false,  ["useable"] = false,["shouldClose"] = false,["description"] = ""},
	["broken_tire"]=          {["name"] = "broken_tire",        ["label"] = "Broken Tire",			["weight"] = 0, ["type"] = "item",  ["image"] = "broken_tire.png",        ["unique"] = false,  ["useable"] = false,["shouldClose"] = false,["description"] = ""},
	["broken_transmission"]=          {["name"] = "broken_transmission",        ["label"] = "Broken Transmission",			["weight"] = 0, ["type"] = "item",  ["image"] = "broken_transmission.png",        ["unique"] = false,  ["useable"] = false,["shouldClose"] = false,["description"] = ""},
	["broken_transmission_cylinder"]=          {["name"] = "broken_transmission_cylinder",        ["label"] = "Broken Cylinder",			["weight"] = 0, ["type"] = "item",  ["image"] = "broken_transmission.png",        ["unique"] = false,  ["useable"] = false,["shouldClose"] = false,["description"] = ""},
	
	--Broken Cosmetics
	["broken_bumper"]=          {["name"] = "broken_bumper",        ["label"] = "Broken Bumper",			["weight"] = 0, ["type"] = "item",  ["image"] = "broken_bumper.png",        ["unique"] = false,  ["useable"] = false,["shouldClose"] = false,["description"] = ""},
	["broken_exhaust"]=          {["name"] = "broken_exhaust",        ["label"] = "Broken Exhaust",			["weight"] = 0, ["type"] = "item",  ["image"] = "broken_exhaust.png",        ["unique"] = false,  ["useable"] = false,["shouldClose"] = false,["description"] = ""},
	["broken_hood"]=          {["name"] = "broken_hood",        ["label"] = "Broken Hood",			["weight"] = 0, ["type"] = "item",  ["image"] = "broken_hood.png",        ["unique"] = false,  ["useable"] = false,["shouldClose"] = false,["description"] = ""},
	["broken_plate"]=          {["name"] = "broken_plate",        ["label"] = "Broken Plates",			["weight"] = 0, ["type"] = "item",  ["image"] = "broken_plate.png",        ["unique"] = false,  ["useable"] = false,["shouldClose"] = false,["description"] = ""},
	["broken_rollcage"]=          {["name"] = "broken_rollcage",        ["label"] = "Broken Rollcage",			["weight"] = 0, ["type"] = "item",  ["image"] = "broken_rollcage.png",        ["unique"] = false,  ["useable"] = false,["shouldClose"] = false,["description"] = ""},
	["broken_roof"]=          {["name"] = "broken_roof",        ["label"] = "Broken Roof",			["weight"] = 0, ["type"] = "item",  ["image"] = "broken_roof.png",        ["unique"] = false,  ["useable"] = false,["shouldClose"] = false,["description"] = ""},
	["broken_seat"]=          {["name"] = "broken_seat",        ["label"] = "Broken Seat",			["weight"] = 0, ["type"] = "item",  ["image"] = "broken_seat.png",        ["unique"] = false,  ["useable"] = false,["shouldClose"] = false,["description"] = ""},
	["broken_skirts"]=          {["name"] = "broken_skirts",        ["label"] = "Broken Skirts",			["weight"] = 0, ["type"] = "item",  ["image"] = "broken_skirts.png",        ["unique"] = false,  ["useable"] = false,["shouldClose"] = false,["description"] = ""},
	["broken_spoiler"]=          {["name"] = "broken_spoiler",        ["label"] = "Broken Spoiler",			["weight"] = 0, ["type"] = "item",  ["image"] = "broken_spoiler.png",        ["unique"] = false,  ["useable"] = false,["shouldClose"] = false,["description"] = ""},
	["broken_headlight"]=          {["name"] = "broken_headlight",        ["label"] = "Broken Headlight",			["weight"] = 0, ["type"] = "item",  ["image"] = "broken_headlight.png",        ["unique"] = false,  ["useable"] = false,["shouldClose"] = false,["description"] = ""},

	--Broken repair parts
	["old_battery"] =            {["name"] = "old_battery",           ["label"] = "Old Battery",				["weight"] = 1000, ["type"] = "item",  ["image"] = "old_battery.png",           ["unique"] = false, ["useable"] = false,["shouldClose"] = false,["description"] = ""},
	["rusty_oil"] =            {["name"] = "rusty_oil",           ["label"] = "Old Oil",				["weight"] = 1200, ["type"] = "item",  ["image"] = "rusty_oil.png",           ["unique"] = false, ["useable"] = false,["shouldClose"] = false,["description"] = ""},
	["rusty_sparkplug"] =            {["name"] = "rusty_sparkplug",           ["label"] = "Old Sparkplug",				["weight"] = 100, ["type"] = "item",  ["image"] = "rusty_sparkplug.png",           ["unique"] = false, ["useable"] = false,["shouldClose"] = false,["description"] = ""},
	
	--Weapon parts
	['trigger'] 				 = {['name'] = 'trigger', 			  	  	['label'] = 'Trigger', 			['weight'] = 200, 		['type'] = 'item', 		['image'] = 'Trigger.png', 			['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},
	['semi_trigger'] 				 = {['name'] = 'semi_trigger', 			  	  	['label'] = 'Semi Trigger', 			['weight'] = 200, 		['type'] = 'item', 		['image'] = 'semi_trigger.png', 			['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},
	['automatic_trigger'] 				 = {['name'] = 'automatic_trigger', 			  	  	['label'] = 'Automatic Trigger', 			['weight'] = 200, 		['type'] = 'item', 		['image'] = 'automatic_trigger.png', 			['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},

	['front_sight'] 				 = {['name'] = 'front_sight', 			  	  	['label'] = 'Front Sight', 			['weight'] = 200, 		['type'] = 'item', 		['image'] = 'front_sight.png', 			['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},
	['rear_sight'] 				 = {['name'] = 'rear_sight', 			  	  	['label'] = 'Rear Sight', 			['weight'] = 200, 		['type'] = 'item', 		['image'] = 'rear_sight.png', 			['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},

	['pistol_barrel'] 	 	 = {['name'] = 'pistol_barrel', 	  		['label'] = 'Pistol Barrel', 	['weight'] = 1500, 		['type'] = 'item', 		['image'] = 'pistol_barrel.png', 				['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},
	['pistol_empty_clip'] 	 	 = {['name'] = 'pistol_empty_clip', 	  		['label'] = 'Pistol MagazineD', 	['weight'] = 1500, 		['type'] = 'item', 		['image'] = 'pistol_empty_clip.png', 				['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},
	['pistol_grip'] 				 = {['name'] = 'pistol_grip', 			  	  	['label'] = 'Pistol Grip', 			['weight'] = 1000, 		['type'] = 'item', 		['image'] = 'pistol_grip.png', 			['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},

	['revolver_barrel'] 	 	 = {['name'] = 'revolver_barrel', 	  		['label'] = 'Revolver Barrel', 	['weight'] = 1500, 		['type'] = 'item', 		['image'] = 'revolver_barrel.png', 				['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},
	['revolver_chamber'] 	 	 = {['name'] = 'revolver_chamber', 	  		['label'] = 'Revolver Chamber', 	['weight'] = 1500, 		['type'] = 'item', 		['image'] = 'revolver_chamber.png', 				['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},
	['revolver_cylinder'] 				 = {['name'] = 'revolver_cylinder', 			  	  	['label'] = 'Revolver Cylinder', 			['weight'] = 1000, 		['type'] = 'item', 		['image'] = 'revolver_cylinder.png', 			['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},
	['revolver_grip'] 				 = {['name'] = 'revolver_grip', 			  	  	['label'] = 'Revolver Grip', 			['weight'] = 1000, 		['type'] = 'item', 		['image'] = 'revolver_grip.png', 			['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},

	['advanced_shotgun_emptyclip'] 				 = {['name'] = 'advanced_shotgun_emptyclip', 			  	  	['label'] = 'Advanced Shotgun Magazine', 			['weight'] = 200, 		['type'] = 'item', 		['image'] = 'advanced_shotgun_emptyclip.png', 			['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},
	['advanced_shotgun_forend'] 				 	 = {['name'] = 'advanced_shotgun_forend', 			  	  	['label'] = 'Advanced Shotgun Forend', 				['weight'] = 1000, 		['type'] = 'item', 		['image'] = 'advanced_shotgun_forend.png', 			['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},
	['advanced_shotgun_grip'] 			 = {['name'] = 'advanced_shotgun_grip', 			['label'] = 'Advanced Shotgun Grip', 	['weight'] = 250, 		['type'] = 'item', 		['image'] = 'advanced_shotgun_grip.png', 			['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},
	['advanced_shotgun_stock'] 				 = {['name'] = 'advanced_shotgun_stock', 			  	  	['label'] = 'Advanced Shotgun Stock', 			['weight'] = 500, 		['type'] = 'item', 		['image'] = 'advanced_shotgun_stock.png', 		['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},

	['assault_rifle_barrel'] 	 	 = {['name'] = 'assault_rifle_barrel', 	  		['label'] = 'Assault Rifle Barrel', 	['weight'] = 1500, 		['type'] = 'item', 		['image'] = 'assault_rifle_barrel.png', 				['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},
	['assault_rifle_buttstock'] 				 = {['name'] = 'assault_rifle_buttstock', 			  	  	['label'] = 'Assault Rifle Buttstock', 			['weight'] = 1000, 		['type'] = 'item', 		['image'] = 'assault_rifle_buttstock.png', 			['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},
	['assault_rifle_emptyclip'] 				 = {['name'] = 'assault_rifle_emptyclip', 			  	  	['label'] = 'Assault Rifle Magazine', 			['weight'] = 200, 		['type'] = 'item', 		['image'] = 'assault_rifle_emptyclip.png', 			['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},
	['assault_rifle_grip'] 				 	 = {['name'] = 'assault_rifle_grip', 			  	  	['label'] = 'Assault Rifle Grip', 				['weight'] = 1000, 		['type'] = 'item', 		['image'] = 'assault_rifle_grip.png', 			['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},
	['assault_rifle_handguard'] 			 = {['name'] = 'assault_rifle_handguard', 			['label'] = 'Assault Rifle Handguard', 	['weight'] = 250, 		['type'] = 'item', 		['image'] = 'assault_rifle_handguard.png', 			['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},
	['assault_rifle_muzzle_break'] 				 = {['name'] = 'assault_rifle_muzzle_break', 			  	  	['label'] = 'Assault Rifle Muzzle', 			['weight'] = 500, 		['type'] = 'item', 		['image'] = 'assault_rifle_muzzle_break.png', 		['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},
	
	['lightmachine_barrel'] 	 	 = {['name'] = 'lightmachine_barrel', 	  		['label'] = 'Light Machine Gun Barrel', 	['weight'] = 1500, 		['type'] = 'item', 		['image'] = 'lightmachine_barrel.png', 				['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},
	['lightmachine_buttstock'] 				 = {['name'] = 'lightmachine_buttstock', 			  	  	['label'] = 'Light Machine Gun Buttstock', 			['weight'] = 1000, 		['type'] = 'item', 		['image'] = 'lightmachine_buttstock.png', 			['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},
	['lightmachine_emptydrum'] 	 	 = {['name'] = 'lightmachine_emptydrum', 	  		['label'] = 'Light Machine Gun Drum Maginze', 	['weight'] = 1500, 		['type'] = 'item', 		['image'] = 'lightmachine_emptydrum.png', 				['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},
	['lightmachine_grip'] 				 = {['name'] = 'lightmachine_grip', 			  	  	['label'] = 'Light Machine Gun Grip', 			['weight'] = 1000, 		['type'] = 'item', 		['image'] = 'lightmachine_grip.png', 			['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},
	['lightmachine_handguard'] 	 	 = {['name'] = 'lightmachine_handguard', 	  		['label'] = 'Light Machine Gun Handguard', 	['weight'] = 1500, 		['type'] = 'item', 		['image'] = 'lightmachine_handguard.png', 				['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},
	['lightmachine_muzzle'] 				 = {['name'] = 'lightmachine_muzzle', 			  	  	['label'] = 'Light Machine Gun Muzzle', 			['weight'] = 1000, 		['type'] = 'item', 		['image'] = 'lightmachine_muzzle.png', 			['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},

	['shotgun_barrel'] 	 	 = {['name'] = 'shotgun_barrel', 	  		['label'] = 'Shotgun Barrel', 	['weight'] = 1500, 		['type'] = 'item', 		['image'] = 'shotgun_barrel.png', 				['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},
	['shotgun_forend'] 				 = {['name'] = 'shotgun_forend', 			  	  	['label'] = 'Shotgun Forend', 			['weight'] = 1000, 		['type'] = 'item', 		['image'] = 'shotgun_forend.png', 			['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},
	['shotgun_grip'] 	 	 = {['name'] = 'shotgun_grip', 	  		['label'] = 'Shotgun Grip', 	['weight'] = 1500, 		['type'] = 'item', 		['image'] = 'shotgun_grip.png', 				['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},

	['sniper_automatic_clip'] 	 	 = {['name'] = 'sniper_automatic_clip', 	  		['label'] = 'Sniper Automatic Magazine', 	['weight'] = 1500, 		['type'] = 'item', 		['image'] = 'sniper_automatic_clip.png', 				['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},
	['sniper_barrel'] 				 = {['name'] = 'sniper_barrel', 			  	  	['label'] = 'Sniper Barrel', 			['weight'] = 1000, 		['type'] = 'item', 		['image'] = 'sniper_barrel.png', 			['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},
	['sniper_bolt_carrier'] 	 	 = {['name'] = 'sniper_bolt_carrier', 	  		['label'] = 'Sniper Bolt Carrier', 	['weight'] = 1500, 		['type'] = 'item', 		['image'] = 'sniper_bolt_carrier.png', 				['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},
	['sniper_buttstock'] 				 = {['name'] = 'sniper_buttstock', 			  	  	['label'] = 'Smiper Buttstock', 			['weight'] = 1000, 		['type'] = 'item', 		['image'] = 'sniper_buttstock.png', 			['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},
	['sniper_muzzle'] 	 	 = {['name'] = 'sniper_muzzle', 	  		['label'] = 'Sniper Muzzle', 	['weight'] = 1500, 		['type'] = 'item', 		['image'] = 'sniper_muzzle.png', 				['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},

	['submachine_barrel'] 	 	 = {['name'] = 'submachine_barrel', 	  		['label'] = 'Submachine Gun Barrel', 	['weight'] = 1500, 		['type'] = 'item', 		['image'] = 'submachine_barrel.png', 				['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},
	['submachine_buttstock'] 				 = {['name'] = 'submachine_buttstock', 			  	  	['label'] = 'Submachine Gun Buttstock', 			['weight'] = 1000, 		['type'] = 'item', 		['image'] = 'submachine_buttstock.png', 			['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},
	['submachine_emptyclip'] 	 	 = {['name'] = 'submachine_emptyclip', 	  		['label'] = 'Submachine Gun Magazine', 	['weight'] = 1500, 		['type'] = 'item', 		['image'] = 'submachine_emptyclip.png', 				['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},
	['submachine_grip'] 				 = {['name'] = 'submachine_grip', 			  	  	['label'] = 'Submachine Gun Grip', 			['weight'] = 1000, 		['type'] = 'item', 		['image'] = 'submachine_grip.png', 			['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Weapons Part'},

	--Keys
    ["methkey"] 					 = {['name'] = 'methkey', 						['label'] = 'Key A', 				    ['weight'] = 200, 		['type'] = 'item', 		['image'] = 'keya.png', 			    ['created'] = nil, 		['decay'] = 14.0,		['unique'] = false, 	['useable'] = false, 	['shouldClose'] = false,   ['combinable'] = nil,   ['description'] = 'Random Key, with "Walter" Engraved on the Back...', ['created'] = nil, ['decay'] = 14.0},
    ["cocainekey"] 					 = {['name'] = 'cocainekey', 					['label'] = 'Key B', 				    ['weight'] = 200, 		['type'] = 'item', 		['image'] = 'keyb.png', 			    ['created'] = nil, 		['decay'] = 14.0,		['unique'] = false, 	['useable'] = false, 	['shouldClose'] = false,   ['combinable'] = nil,   ['description'] = 'Random Key, with a "Razorblade" Engraved on the Back...', ['created'] = nil, ['decay'] = 14.0},
    ["weedkey"] 					 = {['name'] = 'weedkey', 						['label'] = 'Key C', 				    ['weight'] = 200, 		['type'] = 'item', 		['image'] = 'keyc.png', 			    ['created'] = nil, 		['decay'] = 14.0,		['unique'] = false, 	['useable'] = false, 	['shouldClose'] = false,   ['combinable'] = nil,   ['description'] = 'Random Key, with a "Seed" Engraved on the Back...', ['created'] = nil, ['decay'] = 14.0},
	["bunkerkey"] 					 = {['name'] = 'bunkerkey', 						['label'] = 'Bunker Key', 				    ['weight'] = 200, 		['type'] = 'item', 		['image'] = 'bunkerkey.png', 			    ['created'] = nil, 		['decay'] = 14.0,		['unique'] = false, 	['useable'] = false, 	['shouldClose'] = false,   ['combinable'] = nil,   ['description'] = 'A Strange key with a little door of a bunker attached to it...', ['created'] = nil, ['decay'] = 14.0},

	--Money conversion
	['dollarbills1'] 	   			 = {['name'] = 'dollarbills1', 			['label'] = '1k In Cash', 				['weight'] = 1111, 		['type'] = 'item', 		['image'] = '1kdollar.png', 			['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'A Few thousand dollars. Take these to the pawnshops to redeem'},
	['dollarbills10'] 	   			 = {['name'] = 'dollarbills10', 			['label'] = '10k In Cash', 				['weight'] = 1111, 		['type'] = 'item', 		['image'] = '10kdollar.png', 			['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Ten thousands dollars. Take these to the pawnshops to redeem'},
	['dollarbills50'] 	   			 = {['name'] = 'dollarbills50', 			['label'] = '50k In Cash', 				['weight'] = 1111, 		['type'] = 'item', 		['image'] = '50kdollar.png', 			['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Five thousand dollars. Take these to the pawnshops to redeem'},
	['dollarbills100'] 	   			 = {['name'] = 'dollarbills100', 			['label'] = '100k In Cash', 				['weight'] = 1111, 		['type'] = 'item', 		['image'] = '100kdollar.png', 			['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Hundred thousand dollars. Take these to the pawnshops to redeem'},
	['dollarbills500'] 	   			 = {['name'] = 'dollarbills500', 			['label'] = '500k In Cash', 				['weight'] = 1111, 		['type'] = 'item', 		['image'] = '1kdollar.png', 			['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'five hundred thousand dollars. Take these to the pawnshops to redeem'},
	['1gramgold'] 	   			 = {['name'] = '1gramgold', 			['label'] = '1 Gram of Gold', 				['weight'] = 1111, 		['type'] = 'item', 		['image'] = '1g_gold.png', 			['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = '1 gram of gold. Take these to the pawnshops to redeem'},
	['10gramgold'] 	   			 = {['name'] = '10gramgold', 			['label'] = '10 Grams of Gold', 				['weight'] = 1111, 		['type'] = 'item', 		['image'] = '10g_gold.png', 			['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = '10 grams of gold. Take these to the pawnshops to redeem'},
	['50gramgold'] 	   			 = {['name'] = '50gramgold', 			['label'] = '50 Grams of Gold', 				['weight'] = 1111, 		['type'] = 'item', 		['image'] = '50g_gold.png', 			['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = '50 grams of gold. Take these to the pawnshops to redeem'},
	['100gramgold'] 	   			 = {['name'] = '100gramgold', 			['label'] = '100 grams of Gold', 				['weight'] = 1111, 		['type'] = 'item', 		['image'] = '100g_gold.png', 			['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = '100 grams of gold. Take these to the pawnshops to redeem'},
	['500gramgold'] 	   			 = {['name'] = '500gramgold', 			['label'] = '500 grams of Gold', 				['weight'] = 1111, 		['type'] = 'item', 		['image'] = '500g_gold.png', 			['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = '500 grams of gold. Take these to the pawnshops to redeem'},


	(just in case you want the keys iv added them also) - (iv also included my money conversion, you can find the vendor on my github.com/shikohadou it was taken from jim-mining script, also you might like to take a look at my overhall of jim-mining)
}
