QBShared = QBShared or {}
QBShared.Items = {
	---Materials
	--Scraps
	['scrapmetal'] 					 = {['name'] = 'scrapmetal', 			  	  	['label'] = 'Scrap Metal', 				['weight'] = 100, 		['type'] = 'item', 		['image'] = 'metalscrap.png', 			['unique'] = false, 	['useable'] = false, 	['shouldClose'] = false,   ['combinable'] = nil,   ['description'] = 'You can probably make something nice out of this'},
	['scrapcloth'] 					 = {['name'] = 'scrapcloth', 			  	   	['label'] = 'Scrap Cloth', 				['weight'] = 10, 		['type'] = 'item', 		['image'] = 'scrapcloth.png', 				['unique'] = false, 	['useable'] = false, 	['shouldClose'] = false,    ['combinable'] = nil,   ['description'] = 'Scrap Cloth, should be able to make something out of this if i take this somewhere'},
	['scrappaper'] 					 = {['name'] = 'scrappaper', 			  	  	['label'] = 'Scrap Paper', 				['weight'] = 100, 		['type'] = 'item', 		['image'] = 'scrap_paper.png', 			['unique'] = false, 	['useable'] = false, 	['shouldClose'] = false,   ['combinable'] = nil,   ['description'] = 'You can probably make something nice out of this'},
	['scrapplastic'] 					 = {['name'] = 'scrapplastic', 			  	   	['label'] = 'Scrap Plastic', 				['weight'] = 10, 		['type'] = 'item', 		['image'] = 'scrap_plastic.png', 				['unique'] = false, 	['useable'] = false, 	['shouldClose'] = false,    ['combinable'] = nil,   ['description'] = 'Scrap Cloth, should be able to make something out of this if i take this somewhere'},
	['scraprubber'] 					 = {['name'] = 'scraprubber', 			  	  	['label'] = 'Scrap Rubber', 				['weight'] = 100, 		['type'] = 'item', 		['image'] = 'scrap_rubber.png', 			['unique'] = false, 	['useable'] = false, 	['shouldClose'] = false,   ['combinable'] = nil,   ['description'] = 'You can probably make something nice out of this'},
	['scrapglass'] 					 = {['name'] = 'scrapglass', 			  	   	['label'] = 'Scrap Glass', 				['weight'] = 10, 		['type'] = 'item', 		['image'] = 'scrap_glass.png', 				['unique'] = false, 	['useable'] = false, 	['shouldClose'] = false,    ['combinable'] = nil,   ['description'] = 'Scrap Cloth, should be able to make something out of this if i take this somewhere'},
	['scrapewaste'] 					 = {['name'] = 'scrapewaste', 			  	  	['label'] = 'Scrap E-Waste', 				['weight'] = 100, 		['type'] = 'item', 		['image'] = 'scrap_ewaste.png', 			['unique'] = false, 	['useable'] = false, 	['shouldClose'] = false,   ['combinable'] = nil,   ['description'] = 'You can probably make something nice out of this'},
	['scraporganic'] 					 = {['name'] = 'scraporganic', 			  	   	['label'] = 'Scrap Organic', 				['weight'] = 10, 		['type'] = 'item', 		['image'] = 'scrap_organic.png', 				['unique'] = false, 	['useable'] = false, 	['shouldClose'] = false,    ['combinable'] = nil,   ['description'] = 'Scrap Cloth, should be able to make something out of this if i take this somewhere'},
	--Scrap Bags
	['scrapwhitebag'] 					 = {['name'] = 'scrapwhitebag', 			  	  	['label'] = 'White Bin Bag', 				['weight'] = 100, 		['type'] = 'item', 		['image'] = 'scrap_whitebag.png', 			['unique'] = false, 	['useable'] = false, 	['shouldClose'] = false,   ['combinable'] = nil,   ['description'] = 'You can probably make something nice out of this'},
	['scrapblackbag'] 					 = {['name'] = 'scrapblackbag', 			  	   	['label'] = 'Black Bin Bag', 				['weight'] = 100, 		['type'] = 'item', 		['image'] = 'scrap_blackbag.png', 				['unique'] = false, 	['useable'] = false, 	['shouldClose'] = false,    ['combinable'] = nil,   ['description'] = 'Scrap Cloth, should be able to make something out of this if i take this somewhere'},
}
